### ISSUE TITLE
Error noClassDefFoundError

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/openapi-validator#11]
when launching mvn clean package command on latest version several tests fail with this exception:

java.lang.NoClassDefFoundError: com/vordel/common/SystemProperty

[ERROR] Tests run: 24, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 6.675 s <<< FAILURE! - in TestSuite
[ERROR] invalidGetRequestPetsByStatusWithoutQueryParam(com.axway.apim.openapi.validator.TestOpenAPIValidator)  Time elapsed: 0.008 s  <<< FAILURE!
**java.lang.NoClassDefFoundError: com/vordel/common/SystemProperty**
        at com.axway.apim.openapi.validator.TestOpenAPIValidator.invalidGetRequestPetsByStatusWithoutQueryParam(TestOpenAPIValidator.java:96)
**Caused by: java.lang.ClassNotFoundException: com.vordel.common.SystemProperty**
        at com.axway.apim.openapi.validator.TestOpenAPIValidator.invalidGetRequestPetsByStatusWithoutQueryParam(TestOpenAPIValidator.java:96)

[ERROR] isValidRequestFalseTest(com.axway.apim.openapi.validator.TestOpenAPIValidator)  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: expected [false] but found [true]
        at com.axway.apim.openapi.validator.TestOpenAPIValidator.isValidRequestFalseTest(TestOpenAPIValidator.java:55)

[ERROR] testSpecialCharsQueryParam(com.axway.apim.openapi.validator.TestOpenAPIValidator)  Time elapsed: 0.003 s  <<< FAILURE!
**java.lang.NoClassDefFoundError: com/vordel/common/SystemProperty**
        at com.axway.apim.openapi.validator.TestOpenAPIValidator.testSpecialCharsQueryParam(TestOpenAPIValidator.java:261)

[ERROR] validGetRequestPetsByStatusPetstoreSwagger20(com.axway.apim.openapi.validator.TestOpenAPIValidator)  Time elapsed: 0.002 s  <<< FAILURE!
**java.lang.NoClassDefFoundError: com/vordel/common/SystemProperty**
        at com.axway.apim.openapi.validator.TestOpenAPIValidator.validGetRequestPetsByStatusPetstoreSwagger20(TestOpenAPIValidator.java:80)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestOpenAPIValidator.invalidGetRequestPetsByStatusWithoutQueryParam:96 » NoClassDefFound
[ERROR]   TestOpenAPIValidator.isValidRequestFalseTest:55 expected [false] but found [true]
[ERROR]   TestOpenAPIValidator.testSpecialCharsQueryParam:261 » NoClassDefFound com/vord...
[ERROR]   TestOpenAPIValidator.validGetRequestPetsByStatusPetstoreSwagger20:80 » NoClassDefFound
[INFO]
[ERROR] Tests run: 24, Failures: 4, Errors: 0, Skipped: 0

is there a missing Axway Dependency?

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

It is related to missing jar file, fixed it.
