### ISSUE TITLE
Getting initialization error

### ISSUE THREAD

**Issue by venkatesulua1990** [Axway-API-Management-Plus/openapi-validator#6]
I am trying to implement this in V7.7 March 2020 release and getting below error, can you please help 

run filter [Request Validation] {
INFO	4/1/22, 14:55:53.449	                OpenAPIValidator: Creating OpenAPIValidator for: [apiId: 'd6fc783e-19bf-47d4-90a0-12d393f18781', username: 'apiadmin', password: '*******', apiManagerUrl: 'https://localhost:8075']
INFO	4/1/22, 14:55:53.876	                OpenAPIValidator: Loading the original imported API specification from the API Manager using backend API-ID: f12be738-9fa7-4d53-8745-639bd062d78c
ERROR	4/1/22, 14:55:54.226	                java exception:
java.lang.NoClassDefFoundError: Could not initialize class io.swagger.v3.parser.OpenAPIV3Parser
at io.swagger.parser.OpenAPIParser.readContents(OpenAPIParser.java:28)
at com.atlassian.oai.validator.util.OpenApiLoader.readSwaggerParserResult(OpenApiLoader.java:59)
at com.atlassian.oai.validator.util.OpenApiLoader.loadApi(OpenApiLoader.java:39)
at com.atlassian.oai.validator.OpenApiInteractionValidator$Builder.build(OpenApiInteractionValidator.java:541)
at com.axway.apim.openapi.validator.OpenAPIValidator.<init>(OpenAPIValidator.java:100)
at com.axway.apim.openapi.validator.OpenAPIValidator.getInstance(OpenAPIValidator.java:71)
at com.axway.apim.openapi.validator.OpenAPIValidator$getInstance.call(Unknown Source)
at Script15.invoke(Script15.groovy:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
at groovy.lang.Closure.call(Closure.java:414)
at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:374)
at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:368)
at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeImpl(GroovyScriptEngineImpl.java:357)
at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.invokeFunction(GroovyScriptEngineImpl.java:194)
at com.vordel.circuit.script.ScriptProcessor.invoke(ScriptProcessor.java:48)
at com.vordel.circuit.InvocationEngine.invokeFilter(InvocationEngine.java:148)
at com.vordel.circuit.InvocationEngine.invokeCircuit(InvocationEngine.java:40)
at com.vordel.circuit.CircuitDelegateProcessor.invoke(CircuitDelegateProcessor.java:46)
at com.vordel.circuit.InvocationEngine.invokeFilter(InvocationEngine.java:148)
at com.vordel.circuit.InvocationEngine.invokeCircuit(InvocationEngine.java:40)
at com.vordel.circuit.InvocationEngine.recordCircuitInvocation(InvocationEngine.java:278)
at com.vordel.circuit.InvocationEngine.processMessage(InvocationEngine.java:240)
at com.vordel.coreapireg.runtime.broker.InvokableMethod.invoke(InvokableMethod.java:461)
at com.vordel.apiportal.runtime.Broker.invokeMethod(Broker.java:150)
at com.vordel.coreapireg.runtime.CoreApiBroker.processRequest(CoreApiBroker.java:207)
at com.vordel.apiportal.runtime.Broker.processRequest(Broker.java:99)
at com.vordel.apiportal.runtime.virtualized.VApiRuntime.processRequest(VApiRuntime.java:102)
at com.vordel.apiportal.runtime.PortalBroker.processRequest(PortalBroker.java:57)
at com.vordel.dwe.http.HTTPPlugin.invokeDispose(HTTPPlugin.java:438)
at com.vordel.dwe.http.HTTPPlugin.invoke(HTTPPlugin.java:142)

**Comment by cwiechmann** [comment]
I checked the OpenAPI-Validator with the libraries from version 7.7.20200331 and it seems to work from my side. 

Can you please double check, you installed **all** libraries and restarted the API-Gateway processes? It is not sufficient to just restart the API-Gateway instances. The process must be terminated and newly created to load the libraries.

**Comment by venkatesulua1990** [comment]
Yes all jar files moved and can you tell what do you mean by process terminated ?
Before copy killed node manager and instance and after copy restarted both .
-rwxrwxrwx. 1 adm_apigwad2 nvsuser   9783 Jan 28  2020 com.vordel.apiportal.api.portal.model.agnostic.Method.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser  23151 Feb 13  2020 com.vordel.apiportal.runtime.Broker.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser    540 Mar 31  2020 README.txt
-rwxrwxrwx. 1 adm_apigwad2 nvsuser  34402 Apr  4 15:45 jackson-datatype-jdk8-2.10.3.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser  21079 Apr  4 15:45 openapi-validator-1.4.0.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser 105899 Apr  4 15:45 jackson-datatype-jsr310-2.10.1.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser  34769 Apr  4 15:45 swagger-annotations-2.1.2.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser 118249 Apr  4 15:45 swagger-models-2.1.2.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser 165074 Apr  4 15:45 swagger-core-2.1.2.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser  25488 Apr  4 15:45 swagger-parser-v2-converter-2.0.20.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser   6528 Apr  4 15:45 swagger-parser-core-2.0.20.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser   3272 Apr  4 15:45 swagger-parser-2.0.20.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser 133099 Apr  4 15:45 swagger-parser-v3-2.0.20.jar
-rwxrwxrwx. 1 adm_apigwad2 nvsuser 183807 Apr  4 15:45 swagger-request-validator-core-2.11.0.jar
[someuser lib]$ pwd
/apigw/v770/apigateway/ext/lib

**Comment by cwiechmann** [comment]
Killing the process and then restarting the instance should be fine.

**Comment by venkatesulua1990** [comment]
any idea why we are getting the error?

**Comment by cwiechmann** [comment]
It's very likely a Classloading-Problem. Many libraries in the API-Gateway have changed between this and newer version of the platform. I don't have a March-2020 version up and running and only used the tests to validate compatibility with that version. At least, all tests are running fine. Perhaps you have to update to a newer version to make use of this library.

**Comment by venkatesulua1990** [comment]
Thanks Chris, so it will be good to upgrade to latest version and try out right?

**Comment by cwiechmann** [comment]
Yes, that is correct.
